<!DOCTYPE html>
<html>
	<?php $this->partial('head'); ?>
  <body>
		<div id="complete_wrapper">
			<header id="header-wrap" class="row">
			<a href="<?= $this->path('index') ?>"><img src="<?= $this->path('docs/images/logo-header.png'); ?>" alt="logo Carma" /></a>
			<p class="header-login">
				<a href="<?= $this->path('user') ?>" title="Go to your profile">Hi there, <?= $this->user->getGivenname() ?>!</a>
			</p>
         <ul id="mobile_nav">
			<li><a href="#"></a></li>
		</ul>
        <nav id="global_nav" class="row">
			<ul>
            <?php
				
				$page = basename(parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH));
			?>
				<li <?php if ($page == "index"){ echo "class='nav-active'";} ?>><a href="<?= $this->path('index') ?>">Carpools</a></li>
				<li <?php if ($page == "campuses"){ echo "class='nav-active'";} ?>><a href="<?= $this->path('campuses') ?>">Campuses</a></li>
				<li <?php if ($page == "transit"){ echo "class='nav-active'";} ?>><a href="<?= $this->path('transit') ?>">Transit</a></li>
				<li <?php if ($page == "user"){ echo "class='nav-active'";} ?>><a href="<?= $this->path('user') ?>">User</a></li>
			</ul>
		</nav>
        
		</header>
			
			<div id="info-box">
				<h1>Update your profile</h1>
				<p>Update your profile, <?= $this->user->getGivenname(); ?></p>
			</div>
			<div id="page_wrap" class="container row">
				<section id="content_wrap" class="row">
					<article class="col span_8 clr">
						<form id="frmRegister" method="post" action="<?= $this->path('user/updateuser'); ?>">
							<label for="givenname">First Name:</label>
							<input id="givenname" name="givenname" type="text" required title="Vul een geldige voornaam in" value="<?= $this->user->getGivenname() ?>"><br/>
							<label for="familyname">Family Name:</label>
							<input id="familyname" name="familyname" type="text" required title="Vul een geldige familienaam in" value="<?= $this->user->getFamilyname() ?>"><br/>
							<label for="email">Email Address:</label>
							<input id="email" name="email" type="email" required title="Vul een geldig emailadres in" value="<?= $this->user->getEmail() ?>"><br/>
							<label for="pic">Profile Picture (URL):</label>
							<input id="pic" name="pic" type="text" required title="Vul een geldige URL in" value="<?= $this->user->getPic() ?>"><br/>

							<label for="password">Password:</label>
							<input id="password" name="password" type="password" required><br/>
							<input type="hidden" id="id" name="id" value="<?= $this->user->getId() ?>">
							<br/>
							<input id="btnUpdateUser" name="btnUpdateUser" type="submit" value="Update"><br/>
						</form>
					</article>
				</section><!-- content_wrap -->
			</div><!-- page_wrap -->
			<div class="push"></div>
		</div>
		<?php $this->partial('footer'); ?>
  </body>
</html>
