<!DOCTYPE html>
<html>
	<?php $this->partial('head'); ?>
  <body>
		<div id="complete_wrapper">
			<?php $this->partial('header'); ?>
			
			<div id="info-box">
				<h1>Update your profile</h1>
				<p>Update your profile, <?= $this->user->getGivenname(); ?></p>
			</div>
			<div id="page_wrap" class="container row">
				<section id="content_wrap" class="row">
					<article class="col span_8 clr">
						<form id="frmRegister" method="post" action="<?= $this->path('user/updateuser'); ?>">
							<label for="givenname">First Name:</label>
							<input id="givenname" name="givenname" type="text" required title="Vul een geldige voornaam in" value="<?= $this->user->getGivenname() ?>"><br/>
							<label for="familyname">Family Name:</label>
							<input id="familyname" name="familyname" type="text" required title="Vul een geldige familienaam in" value="<?= $this->user->getFamilyname() ?>"><br/>
							<label for="email">Email Address:</label>
							<input id="email" name="email" type="email" required title="Vul een geldig emailadres in" value="<?= $this->user->getEmail() ?>"><br/>
							<label for="pic">Profile Picture (URL):</label>
							<input id="pic" name="pic" type="text" required title="Vul een geldige URL in" value="<?= $this->user->getPic() ?>"><br/>

							<label for="password">Password:</label>
							<input id="password" name="password" type="password" required><br/>
							<input type="hidden" id="id" name="id" value="<?= $this->user->getId() ?>">
							<br/>
							<input id="btnUpdateUser" name="btnUpdateUser" type="submit" value="Update"><br/>
						</form>
					</article>
				</section><!-- content_wrap -->
			</div><!-- page_wrap -->
			<div class="push"></div>
		</div>
		<?php $this->partial('footer'); ?>
  </body>
</html>
