<!DOCTYPE html>
<html>
	<?php $this->partial('head'); ?>
  <body>
		<div id="complete_wrapper">
		<?php $this->partial('header'); ?>
			
			<div id="info-box">
				<h1>Log In</h1>
				<p>Please enter your credentials (your email address and your password) to continue. If you haven't registered yet, you can always sign up to carma, for free.</p>
				<p>
				<?php 
				if (isset($_SESSION["Error"]))
				{
					echo $_SESSION["Error"]; 
				} 
				?>
				</p>
			</div>
			<div id="page_wrap" class="container row">
				<section id="content_wrap" class="row">
					<article class="col span_8 clr">
						<form id="frmLogin" method="post" action="">
							<label for="email">Email:</label>
							<input id="email" name="email" type="email" required title="Vul een geldig emailadres in" value="<?= @$_POST['email'] ?>"><br/>
							<label for="password">Password:</label>
							<input id="password" required name="password" type="password"><br/>
							<br/>
							<input id="btnLogin" name="btnLogin" type="submit" value="Log In">
						</form>
						<br/>
						<a href="<?= $this->path('user/register') ?>">No account yet? Register now!</a>
						<br/>
						
					</article>
				</section><!-- content_wrap -->
			</div><!-- page_wrap -->
			<div class="push"></div>
		</div>
		<?php $this->partial('footer'); ?>
  </body>
</html>
