<!DOCTYPE html>
<html lang="nl">
	<?php $this->partial('head'); ?>
	<body>
		<div id="complete_wrapper">
		<header id="header-wrap" class="row">
			<a href="<?= $this->path('index') ?>"><img src="<?= $this->path('docs/images/logo-header.png'); ?>" alt="logo Carma" /></a>
			<p class="header-login">
				<a href="<?= $this->path('user') ?>" title="Log in">Log in</a>
			</p>
         <ul id="mobile_nav">
			<li><a href="#"></a></li>
		</ul>
        <nav id="global_nav" class="row">
			<ul>
            <?php
				
				$page = basename(parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH));
			?>
				<li <?php if ($page == "index"){ echo "class='nav-active'";} ?>><a href="<?= $this->path('index') ?>">Carpools</a></li>
				<li <?php if ($page == "campuses"){ echo "class='nav-active'";} ?>><a href="<?= $this->path('campuses') ?>">Campuses</a></li>
				<li <?php if ($page == "transit"){ echo "class='nav-active'";} ?>><a href="<?= $this->path('transit') ?>">Transit</a></li>
				<li <?php if ($page == "user"){ echo "class='nav-active'";} ?>><a href="<?= $this->path('user') ?>">User</a></li>
			</ul>
		</nav>
        
		</header>
	
		<div id="info-box">
				<h1>We are very sorry, but an error occurred.</h1>
				<p><?php
								if (isset($_SESSION['error']))
								{ echo $_SESSION['error']['text']; }
								else if (isset($_POST['email']))
								{ echo "Thanks for filling in the form."; }
								else { echo "404: Page Not Found"; }
								 ?></p>
		</div>
		<div id="page_wrap" class="container row">
			<section id="content_wrap" class="row">
				<article class="col span_8 clr">
					<?php
						if (isset($_POST['email']) && isset($_SESSION['error']) )
						//if "email" is filled out, send email
							{
							//send email
							$email = $_POST['email'] ;
							$subject = $_POST['subject'] ;
							$message = "Error: " . $_POST['error'] . " Error given on " . $_POST['page'] . " Message: " . $_POST['message'] ;
							mail("jdw.jensdewulf@gmail.com", $subject,
							$message, "From:" . $email);
							}
						else if (isset($_SESSION['error']))
						//if "email" is not filled out, display the form
							{
							$page = $_SESSION["error"]["page"];
							$error =  $_SESSION["error"]["text"];
							
							// DESTROY SESSION FOR NEXT ERROR
							unset($_SESSION['error']);
							echo "<p>It seems like you got yourself in a mess here. Perhaps returning to the previous page might help you.</p>";
							echo "<form method='post' action='" . $this->path('error') . "'>
							<label for='email'>Email:</label>
							<input name='email' type='text'><br>
							<input hidden name='error' value='$error' type='text'>
							<input hidden name='page' value='$page' type='text'>
							<label for='subject'>Subject:</label>
							<input name='subject' type='text'><br>
							<label for='message'>Message:</label>
							<textarea name='message'></textarea><br>
							<input type='submit'>
							</form>";
							}
						else
						{
							echo "<p class='error_notice'>It seems like you got yourself in a mess here. Perhaps returning to the previous page might help you.</p>";
						}
						?>		
				</article>
			</section><!-- content_wrap -->
			
		</div><!-- page_wrap -->
		<div class="push"></div>
		</div>
		<?php $this->partial('footer'); ?>
	</body>
</html>