<!DOCTYPE html>
<html lang="nl">
	<head>
		<meta charset="utf-8">
		<title>carma</title>
		<!-- mobile VIEWPORT -->
		<meta name="viewport" content="width=device-width,initial-scale=1">
		<link rel="stylesheet" href="<?= $this->path('css/index.css'); ?>">
		<!-- GOOGLE MAPS -->
		<!-- STRING IN JAVASCRIPT DUMPEN, HARD GECODEERD -->
		<script src="http://maps.google.com/maps/api/js?v=3&sensor=false" type="text/javascript"></script>
		<script>var latCampus = "<?= $this->campus->getLat() ?>"</script>
		<script>var lngCampus = "<?= $this->campus->getLng() ?>"</script>
	</head>
	<body>
		<div id="complete_wrapper">
		<header id="header-wrap" class="row">
			<a href="<?= $this->path('index') ?>"><img src="<?= $this->path('docs/images/logo-header.png'); ?>" alt="logo Carma" /></a>
			<p class="header-login">
				<?php if ($this->hasIdentity) { ?>
					<a href="<?= $this->path('user') ?>" title="Go to your profile">Hi there, <?= $this->user->getGivenname() ?>!</a>
				<?php } else { ?>
					<a href="<?= $this->path('user') ?>" title="Log in">Log in</a>
				<?php } ?>
			</p>
        <ul id="mobile_nav">
			<li><a href="#"></a></li>
		</ul>
		<nav id="global_nav" class="row">
			<ul>
				<li><a href="<?= $this->path('index') ?>">Carpools</a></li>
				<li class="nav-active"><a href="<?= $this->path('campuses') ?>">Campuses</a></li>
				<li><a href="<?= $this->path('user') ?>">User</a></li>
			</ul>
		</nav>
		</header>
		
		<div id="info-box" class="info-0botmarg">
			<h1><?= $this->campus->getName() ?></h1>
		</div>
		<div id="page_wrap" class="container row">
		<section class="row">
			<article class="col span_8 clr">
			<h2>Campus picture</h2>
			<p><img class="campus_img" src="<?= $this->campus->getPic() ?>"></p>
			<h2>Location</h2>
			<div id="mapTest" class="right clearfix"></div>
			</article>
			<article class="col span_4 clr">
			
			<h2>Campus location</h2>
			<p>Address: <?= $this->campus->getAddress() ?></p>
			<p>City: <?= $this->campus->getCity() ?></p>
			<p>Postal: <?= $this->campus->getPostal() ?></p>
			<h2>Campus details</h2>
			<p>Telephone: <?= $this->campus->getTelephone() ?></p>
			<p>Latitude: <?= $this->campus->getLat() ?></p>
			<p>Longitude: <?= $this->campus->getLng() ?></p>
			</article>
			</section>
		</div><!-- page_wrap -->
		<div class="push"></div>
		</div>
		<?php $this->partial('footer'); ?>
		<script src="<?= $this->path('js/mylibs/drawCampus.js') ?>"></script>
	</body>
</html>
