<!DOCTYPE html>
<html lang="nl">

	<?php $this->partial('head'); ?>
	<body>
		<div id="complete_wrapper">
			<?php $this->partial('header'); ?>
			
			
			<div id="info-box">
				<p>Carma is digital platform where you can setup a carpool ride to your campus in no time. And all the public transit info is available here as well. Here is a full list of all the campuses:</p>
			</div>
			<div id="page_wrap" class="container row">
				<section class="row">
					<?php if (empty($this->campuses)) { ?>
						<p>There are no campuses in the database yet!</p>
					<?php } else {
						?>
						<div class='search'>
							<input type="text" id="input" onfocus="this.value = '';" value="Start searching..." />
						</div>
						<ul class="filter">
							<?php
							foreach ($this->campuses as $campus) {
								?>
								<li data-label='<?= strtolower($campus->getName()) ?>'><a href="<?= $this->path('campuses/campus/id/' . $campus->getId()) ?>"><?= $campus->getName() ?></a></li>
								<?php
							}
						}
						?>
					</ul>
				</section>
				

			</div><!-- page_wrap -->
			<div class="push"></div>
		</div>
		<?php $this->partial('footer'); ?>
		<script>
								jQuery(document).ready(function($) {
									$('#input').on("keyup", function() {
										var input = $(this).val().toLowerCase();

										$("ul.filter li").show();
										$("ul.filter li").not("[data-label*=" + input + "]").hide();

										if (input == '') {
											$("ul.filter li").show();
										}
									});
								});
		</script>
	</body>
</html>
