<!DOCTYPE html>
<html lang="nl">
	<?php $this->partial('head'); ?>
	<body>
		<div id="complete_wrapper">
        <?php $this->partial('header'); ?>
		<div id="info-box">
		<p>Carma is digital platform where you can setup a carpool ride to your campus in no time. And all the public transit info is available here as well.</p>
		<?php if (!$this->hasIdentity) { ?>
			<p><a href="<?= $this->path('user'); ?>">&raquo; Would you like to join a carpool or make one ? Register or Login today!</a></p>
		<?php } ?>
        <?php if ($this->hasIdentity) { ?>
			<p><a href="<?= $this->path('carpools/newcarpool'); ?>">&raquo; Make your own carpool!</a></p>
		<?php } ?>
		</div>
		<div id="page_wrap" class="container row">
				<?php $count = 0; foreach ($this->carpools as $carpool) { ?>
				<?php 
					if($count === 0 || $count % 4 === 0)
					{ 
					echo '<section class="row carpool">';
					} 
					$count++;
				?>
					<article class="carpool col span_4 clr  article_cont">
                    <p class="index-seats"><strong><?= $carpool->getSeats() ?></strong> seats</p>
						<a href="<?= $this->path('carpools/carpool/id/' . $carpool->getId()) ?>"><figure style="background: url('<?= $carpool->getCampus()->getPic() ?>')" ></figure></a>
							<section class="article_text">
							<h2><a href="<?= $this->path('carpools/carpool/id/' . $carpool->getId()) ?>">
									<?php
										if (strlen($carpool->getTitle()) > 19)
										{
											echo substr($carpool->getTitle(), 0, 17) . '...' ;
										}
										else
										{
											echo $carpool->getTitle();
										}
									?>
								</a></h2>
							<h3><a href="<?= $this->path('campuses/campus/id/' . $carpool->getCampus()->getId()) ?>"><?= $carpool->getCampus()->getName() ?></a></h3>
                            <h3><?= $carpool->getUser()->getGivenname() ?> <?= $carpool->getUser()->getFamilyname() ?></h3>
							</section>
						<br/></div>
					</article>
				<?php if($count === 0 || $count % 4 === 0)
					{ 
					echo '</section>';
					}
				?>
				<?php } ?>
			
		</div><!-- page_wrap -->
		<div class="push"></div>
		</div><!-- complete wrapper -->
		<?php $this->partial('footer'); ?>
		</body>
</html>