<footer class="footer" data-role="footer" data-position="fixed">
	<p>Copyright © <?= date('Y') ?> <a href="http://twitter.com/dewulfjens">Jens De Wulf</a> &amp; <a href="http://www.arteveldehogeschool.be/">Artevelde University College Ghent</a>.</p>
</footer>
<!-- BOTTOM SCRIPTS -->
<script src="<?= $this->path('js/vendor/jquery-2.0.0.js'); ?>"></script>
<script src="<?= $this->path('js/vendor/jquery.timeago.js'); ?>"></script>
<script src="<?= $this->path('js/mylibs/index.js'); ?>"></script>