<head>
	<meta charset="utf-8">
	<title>Carma</title>
	<!-- APPLE iOS ICON -->
	<link rel="apple-touch-icon-precomposed" href="<?= $this->path('css/images/apple-touch-icon.png'); ?>"/>
	<!-- mobile VIEWPORT -->
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<link rel="stylesheet" href="<?= $this->path('css/index.css'); ?>">
	<!-- GOOGLE MAPS
  <script src="http://maps.google.com/maps/api/js?v=3&sensor=false" type="text/javascript"></script>
	-->
</head>