<!DOCTYPE html>
<html>
		<head>
		<meta charset="utf-8">
        <title>Carma</title>
        <!-- APPLE iOS ICON -->
        <link rel="apple-touch-icon-precomposed" href="<?= $this->path('css/images/apple-touch-icon.png'); ?>"/>
        <!-- mobile VIEWPORT -->
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <link rel="stylesheet" href="<?= $this->path('css/index.css'); ?>">
		<!-- GOOGLE MAPS -->
		<!-- STRING IN JAVASCRIPT DUMPEN, HARD GECODEERD -->
		<script src="http://maps.google.com/maps/api/js?v=3&sensor=false" type="text/javascript"></script>		
	</head>
  <body>
		<div id="complete_wrapper">
			<?php $this->partial('header'); ?>
		
			<div id="info-box">
            <h1>So you want to use public transit ?</h1>
				<p>Select a campus from the list and we'll give you directions to get to your campus from your current location.</p>
			</div>
			<div id="page_wrap" class="container row">
				<section id="content_wrap" class="row">
					<article class="span_12 clr">
						<h2>Campuses</h2>
                        <div id="control">
						<select id="campus" name="campus" onchange="calcRouteTransit()">
							<?php foreach ($this->campuses as $campus) { ?>
                                <option value="<?= $campus->getLat(); ?>,<?= $campus->getLng(); ?>"><?= $campus->getName(); ?></option>
                            <?php } ?>
                        </select>
                        </div>
						<br/>
                    </article>
                    <article class="col span_8 clr"><div id="mapTest" class="right clearfix"></div></article>
                    <article class="col span_3 clr">
                    <div id="directionsPanel"></div>
					</article>
					</section><!-- content_wrap -->
			</div><!-- page_wrap -->
			<div class="push"></div>
		</div>
		<?php $this->partial('footer'); ?>
  </body>
</html>
