<!DOCTYPE html>
<html>
		<head>
		<meta charset="utf-8">
        <title>Carma</title>
        <!-- APPLE iOS ICON -->
        <link rel="apple-touch-icon-precomposed" href="<?= $this->path('css/images/apple-touch-icon.png'); ?>"/>
        <!-- mobile VIEWPORT -->
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <link rel="stylesheet" href="<?= $this->path('css/index.css'); ?>">
		<!-- GOOGLE MAPS -->
		<!-- STRING IN JAVASCRIPT DUMPEN, HARD GECODEERD -->
		<script src="http://maps.google.com/maps/api/js?v=3&sensor=false" type="text/javascript"></script>		
	</head>
  <body>
		<div id="complete_wrapper">
			<?php $this->partial('header'); ?>
		
			<div id="info-box">
				<h1>Hello there, <?= $this->user->getGivenname() ?>.</h1>
				<p>You have reached your profile page. </p>
			</div>
			<div id="page_wrap" class="container row">
				<section id="content_wrap" class="row">
					<article class="col span_5 clr" id="profile">
						<h2>Campuses</h2>
                        <div id="control">
						<select id="campus" name="campus" onchange="calcRouteTransit()">
							<?php foreach ($this->campuses as $campus) { ?>
                                <option value="<?= $campus->getLat(); ?>,<?= $campus->getLng(); ?>"><?= $campus->getName(); ?></option>
                            <?php } ?>
                        </select>
                        </div>
						<br/>
					</article>
                    <div id="mapTest" class="right clearfix"></div>
                    <article class="col span_4 clr" id="profile">
                    <div id="directions-panel"></div>
                    </article>
						
					</section><!-- content_wrap -->
			</div><!-- page_wrap -->
			<div class="push"></div>
		</div>
		<?php $this->partial('footer'); ?>
  </body>
</html>
