
<!DOCTYPE html>
<html lang="nl">
	<head>
		<meta charset="utf-8">
        <title>Carma</title>
        <!-- APPLE iOS ICON -->
        <link rel="apple-touch-icon-precomposed" href="<?= $this->path('css/images/apple-touch-icon.png'); ?>"/>
        <!-- mobile VIEWPORT -->
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <link rel="stylesheet" href="<?= $this->path('css/index.css'); ?>">
		<!-- GOOGLE MAPS -->
		<!-- STRING IN JAVASCRIPT DUMPEN, HARD GECODEERD -->
		<script src="http://maps.google.com/maps/api/js?v=3&sensor=false" type="text/javascript"></script>
		<script>var latCampus = <?= $this->carpool->getCampus()->getLat() ?></script>
		<script>var lngCampus = <?= $this->carpool->getCampus()->getLng() ?></script>
		<script>var latDepart = <?= $this->carpool->getLat() ?></script>
		<script>var lngDepart = <?= $this->carpool->getLng() ?></script>
		
	</head>
	<body onload="initialize()">
		<div id="complete_wrapper">
		<?php $this->partial('header'); ?>
		<div id="info-box" class="info-0botmarg">
			<h1><?= $this->carpool->getTitle() ?></h1>
		</div>
		<div id="page_wrap" class="container row">
			<section id="content_wrap" class="row">
            <article class="col span_8 clr">
			<h2><a href="<?= $this->path('campuses/campus/id/' . $this->carpool->getCampus()->getId()) ?>"><?= $this->carpool->getCampus()->getName() ?></a></h2>
			<p><a href="<?= $this->path('campuses/campus/id/' . $this->carpool->getCampus()->getId()) ?>"><img alt="<?= $this->carpool->getTitle() ?>" src="<?= $this->carpool->getCampus()->getPic() ?>"/></a>  </p>
			<h2>Route</h2>
			<div id="mapTest" class="right clearfix"></div>
			</article>
			<article class="col span_3 clr">
			
			<h2>Departure location</h2>
			<p>Address: <?= $this->carpool->getDeparture() ?></p>
			<p>Latitude: <?= $this->carpool->getLat() ?></p>
			<p>Longitude: <?= $this->carpool->getLng() ?></p>
            
			<h2>Carpool details</h2>
            <p>Carpool User: <?= $this->carpool->getUser()->getGivenname() ?> <?= $this->carpool->getUser()->getFamilyname() ?></p>
            <p>Description: <?= $this->carpool->getDescription() ?></p>
			<p>Mail: <?= $this->carpool->getUser()->getEmail() ?></p>
			</article>
            <article class="col span_3 clr">
			
			<h2>Campus location</h2>
			<p>Address: <?= $this->carpool->getCampus()->getAddress() ?></p>
			<p>City: <?= $this->carpool->getCampus()->getCity() ?></p>
			<p>Postal: <?= $this->carpool->getCampus()->getPostal() ?></p>
			<h2>Campus details</h2>
			<p>Telephone: <?= $this->carpool->getCampus()->getTelephone() ?></p>
			<p>Latitude: <?= $this->carpool->getCampus()->getLat() ?></p>
			<p>Longitude: <?= $this->carpool->getCampus()->getLng() ?></p>
			</article>
			<article class="col span_6 clr">
				<form method="post" action="<?= $this->path('carpools/carpool/id/' . $this->carpool->getId()) ?>">
						<?php 
						$campus_id = $this->carpool->getCampus()->getId();
						if(isset( $_POST['Apply'] ))
							{ echo "You have applied for this Carpool";}
						else if(isset( $_POST['approved']) )
							{ echo "You have been approved for this carpool. You can always leave this carpool by using the leave button. ";
							echo '<input name="leave" type="submit" value="Leave">';}
						else if (!$this->hasIdentity)
							{ echo '<p class="FakeBtn">Log in to apply for the Carpool </p> <br />'; }
						else { echo '<input name="apply" type="submit" value="Apply">'; }
						
						?>
					</form>
				</article>
			
			</section><!-- content_wrap -->
		</div><!-- page_wrap -->
		<div class="push"></div>
		</div>
		<?php $this->partial('footer'); ?>        
		<script src="<?= $this->path('js/mylibs/drawRoute.js') ?>" type="text/javascript"></script>
	</body>
</html>