<!DOCTYPE html>
<html lang="nl">
	<?php $this->partial('head'); ?>
	<body>
		<div id="complete_wrapper">
		<?php $this->partial('header'); ?>
        <div id="info-box">
			<p>Edit carpool</p>
		</div>
		<div id="page_wrap" class="container row">
			<section id="content_wrap" class="row">
				<article class="col span_8 clr">
					<form id="frmUpdateCarpool" method="post" action="<?= $this->path('carpool/updatecarpool') ?>">
						<input id="id" name="id" type="hidden" value="<?= $this->carpool->getId() ?>">

						<label for="title">Title:</label>
						<input id="title" name="title" type="text" required value="<?= $this->carpool->getTitle() ?>">

						<label for="description">Description:</label>
						<textarea id="description" name="description" required><?= $this->carpool->getDescription() ?></textarea>

						<label for="departure">Departure:</label>
						<textarea id="departure" name="departure" required><?= $this->carpool->getDeparture() ?></textarea>
						
                        <label for="lat">Departure Latitude:</label>
						<input id="lat" name="lat" type="text" required value="<?= $this->carpool->getLat() ?>">

						<label for="lng">Departure Longitude:</label>
						<input id="lng" name="lng" type="text" required value="<?= $this->carpool->getLng() ?>">
                        
						<label for="seats">Seats:</label>
						<input id="seats" name="seats" type="number" required value="<?= $this->carpool->getSeats() ?>">

						<label for="campus">Campus:</label>
						<select id="campus" name="campus">
							<?php foreach ($this->campuses as $campus) { ?>
								<option value="<?= $campus->getId(); ?>"><?= $campus->getName(); ?></option>
							<?php } ?>
						</select>

						<label for="user">Owner:</label>
                        <label id="user" name="user"><?= $this->carpool->getUser()->getGivenname() ?> <?= $this->carpool->getUser()->getFamilyname() ?></label>
                        
						<input id="btnUpdateCarpool" name="btnUpdateCarpool" type="submit" value="Update carpool">
					</form>
				</article>
			</section><!-- content_wrap -->
			<footer class="row">
				<?php $this->partial('footer'); ?>
			</footer>
		</div><!-- page_wrap -->	
  </body>
</html>