<!DOCTYPE html>
<html lang="nl">
	<?php $this->partial('head'); ?>
	<body>
		<div id="complete_wrapper">
		<?php $this->partial('header'); ?>
		
		<div id="info-box">
		<p>Here you can find all carpools on carma.</p>
		</div>
		<div id="page_wrap" class="container row">
				<?php $count = 0; foreach ($this->carpools as $carpool) { ?>
				<?php 
					if($count === 0 || $count % 4 === 0)
					{ 
					echo '<section class="row carpool">';
					} 
					$count++;
				?>
					<article class="carpool col span_3 clr  article_cont">
						<figure style="background: url('<?= $carpool->getCampus()->getPic() ?>')" ></figure>
							<section class="article_text">
							<h2><a href="<?= $this->path('carpools/carpool/id/' . $carpool->getId()) ?>">
									<?php
										if (strlen($carpool->getTitle()) > 19)
										{
											echo substr($carpool->getTitle(), 0, 17) . '...' ;
										}
										else
										{
											echo $carpool->getTitle();
										}
									?>
								</a></h2>
							<h3><a href="<?= $this->path('campuses/campus/id/' . $carpool->getCampus()->getId()) ?>"><?= $carpool->getCampus()->getName() ?></a></h3>
							</section>
						<br/>
						<br/></div>
					</article>
				<?php if($count === 0 || $count % 4 === 0)
					{ 
					echo '</section>';
					}
				?>
				<?php } ?>
			
		</div><!-- page_wrap -->
			<div class="push"></div>
		</div><!-- complete wrapper -->
		<?php $this->partial('footer'); ?>
		<script src="<?= $this->path('js/vendor/jquery.countdown.js'); ?>"></script>
		<script src="<?= $this->path('js/mylibs/countdown.js'); ?>"></script>
	</body>
</html>