<!DOCTYPE html>
<html lang="nl">
	<?php $this->partial('head'); ?>
	<body>
		<div id="complete_wrapper">
		<?php $this->partial('header'); ?>
		<div id="info-box">
			<p>Add your carpool</p>
		</div>
		<div id="page_wrap" class="container row">
		<section id="content_wrap" class="row">
			<article class="col span_8 clr">
		<form id="frmNewCarpool" method="post" action="">
			<label for="title">Title:</label>
			<input id="title" name="title" type="text" required value="<?= @$_POST['title'] ?>">

			<label for="description">Description:</label>
			<textarea id="description" name="description" required><?= @$_POST['description']?></textarea>

			<label for="departure">Departure Name:</label>
			<textarea id id="departure" name="departure" required ><?= @$_POST['departure'] ?></textarea>

			<label for="lat">Departure Latitude:</label>
			<input id="lat" name="lat" type="text" required value="<?= @$_POST['lat'] ?>">

			<label for="lng">Departure Longitude:</label>
			<input id="lng" name="lng" type="text" required value="<?= @$_POST['lng'] ?>">
            
			<label for="seats">Seats:</label>
			<input id="seats" name="seats" type="number" required value="<?= @$_POST['seats'] ?>">

			<label for="campus">Campus:</label>
			<select id="campus" name="campus">
				<?php foreach ($this->campuses as $campus) { ?>
					<option value="<?= $campus->getId(); ?>"><?= $campus->getName(); ?></option>
				<?php } ?>
			</select>
			
            <label for="user">User:</label>
			<label id="userLbl" name="userLbl"><?= $this->user->getGivenname() ?> <?= $this->user->getFamilyname() ?></label>
            <input id="user" name="user" type="hidden" value="<?= $this->user->getId() ?>">
			<input id="btnNewCarpool" name="btnNewCarpool" type="submit" value="Add carpool">
		</form>
		</article>
		</section><!-- content_wrap -->
		<footer class="row">
		<?php $this->partial('footer'); ?>
		</footer>
		</div><!-- page_wrap -->	
  </body>
</html>